export const SET_TREE = 'SET_TREE';
export const SET_PARENT_NAME = 'SET_PARENT_NAME';
export const ADD_PARENT = 'ADD_PARENT';
export const ADD_CHILD = 'ADD_CHILD';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const SELECT_COMPONENT = 'SELECT_COMPONENT';